### ISSUE TITLE
Docker image v0.17.0 fails to run

### ISSUE THREAD

**Issue by Harshit-9398** [debiai/debiai#52]
Hello,  
I am trying to run the DebiAI in an Openshift cluster using the docker image v0.17.0, but it seems there is some issue of a python package in the image.  
I got the following error logs:
```
Traceback (most recent call last):
  File "websrv.py", line 1, in <module>
    import connexion
  File "/usr/local/lib/python3.8/site-packages/connexion/__init__.py", line 5, in <module>
    from .apis import AbstractAPI  # NOQA
  File "/usr/local/lib/python3.8/site-packages/connexion/apis/__init__.py", line 1, in <module>
    from .abstract import AbstractAPI  # NOQA
  File "/usr/local/lib/python3.8/site-packages/connexion/apis/abstract.py", line 13, in <module>
    from ..operations import make_operation
  File "/usr/local/lib/python3.8/site-packages/connexion/operations/__init__.py", line 1, in <module>
    from .abstract import AbstractOperation  # noqa
  File "/usr/local/lib/python3.8/site-packages/connexion/operations/abstract.py", line 9, in <module>
    from ..decorators.response import ResponseValidator
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/response.py", line 11, in <module>
    from .validation import ResponseBodyValidator
  File "/usr/local/lib/python3.8/site-packages/connexion/decorators/validation.py", line 13, in <module>
    from ..json_schema import Draft4RequestValidator, Draft4ResponseValidator
  File "/usr/local/lib/python3.8/site-packages/connexion/json_schema.py", line 6, in <module>
    from openapi_spec_validator.handlers import UrlHandler
ModuleNotFoundError: No module named 'openapi_spec_validator.handlers'
```

Can you please point us to the correct image?

**Comment by Tomansion** [comment]
Thank you for noticing, a fix is on the way

**Comment by Tomansion** [comment]
**debiai/app:0.17.2** or **debiai/app:latest**  should work fine, sorry for the inconvenience

**Comment by Harshit-9398** [comment]
Thanks for the help, I tested the latest image and it works fine! 👍🏽   
So, I am closing this issue.
